services:
  postgres:
    image: postgres:17.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: InstaCar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2

volumes:
  postgres_data:
